package builtin

const (
	StoreToolResearcher       = "turn:researcher"
	StoreQuotaReads           = "gauge:quota_reads"
	StoreExploreScore         = "gauge:explore"
	StoreTasksAllDone         = "gauge:tasks_done"
	StoreHasTasks             = "turn:has_tasks"
	StoreTurnToolCalls        = "turn:tool_calls"
	StoreStepInputLen         = "turn:step_len"
	StoreStepInput            = "value:step"
	StoreExploreCalls         = "counter:explore_calls"
	StoreHasEdits             = "turn:has_edits"
	StoreRespGarbled          = "counter:garbled"
	StoreLedgerModified       = "gauge:ledger_modified"
	StoreLedgerVerified       = "gauge:ledger_verified"
	StoreLedgerErrors         = "gauge:ledger_errors"
	StoreLedgerNonDocModified = "gauge:ledger_nondoc_modified"
	StoreLedgerProgress       = "turn:ledger_progress"
	StoreFinalAnswerText      = "value:final_answer"
	StoreToolResultCount      = "gauge:tool_results"
	StoreEditTargetPath       = "value:edit_target_path"
	StoreEditTargetExists     = "turn:edit_target_exists"
	StoreEditTargetWasRead    = "turn:edit_target_was_read"
	StoreEditAnchorSufficient = "turn:edit_anchor_sufficient"
	StoreReadOnlyStreak       = "turn:read_only_streak"

	CounterQuotaWarned      = "counter:quota_warned"
	CounterVerifyInjected   = "counter:verify_injected"
	CounterExploreInjected  = "counter:explore_injected"
	CounterStallTurns       = "counter:stall_turns"
	CounterQualityWarned    = "counter:quality_warned"
	CounterToolResultWarned = "counter:tool_result_warned"

	PolicyExploreExhausted = "policy:explore_exhausted"
)
