// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';
import {config} from '../models';
import {session} from '../models';

export function Abort():Promise<void>;

export function ClearSelectedSkill():Promise<void>;

export function ContextReport():Promise<string>;

export function ContextSnapshot():Promise<common.ContextSnapshot>;

export function ContextStatus():Promise<string>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetConfig():Promise<config.View>;

export function GetSkillManagement():Promise<common.SkillManagementView>;

export function ListSessions():Promise<Array<session.Meta>>;

export function LoadSession(arg1:string):Promise<Array<common.DisplayMessage>>;

export function NewSession():Promise<session.Meta>;

export function ProviderModel():Promise<string>;

export function ReadImageBase64(arg1:string):Promise<string>;

export function RefreshSkillManagement():Promise<common.SkillManagementView>;

export function ReplyConfirm(arg1:string,arg2:boolean):Promise<void>;

export function ReplyQuestion(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SaveConfig(arg1:config.View):Promise<config.View>;

export function SelectSkill(arg1:string):Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function SetPluginEnabled(arg1:string,arg2:boolean):Promise<common.SkillManagementView>;

export function SwitchModel(arg1:string):Promise<string>;
