// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {session} from '../models';
import {common} from '../models';

export function Abort():Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetConfig():Promise<app.ConfigSnapshot>;

export function GetSkillManagement():Promise<app.SkillManagementSnapshot>;

export function ListSessions():Promise<Array<session.Meta>>;

export function LoadSession(arg1:string):Promise<Array<common.DisplayMessage>>;

export function NewSession():Promise<session.Meta>;

export function ProviderModel():Promise<string>;

export function ReadImageBase64(arg1:string):Promise<string>;

export function RefreshSkillManagement():Promise<app.SkillManagementSnapshot>;

export function ReplyConfirm(arg1:string,arg2:boolean):Promise<void>;

export function ReplyQuestion(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SaveConfig(arg1:app.ConfigSnapshot):Promise<app.ConfigSnapshot>;

export function SendMessage(arg1:string):Promise<void>;

export function SetPluginEnabled(arg1:string,arg2:boolean):Promise<app.SkillManagementSnapshot>;
