// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {protocol} from '../models';
import {runtime} from '../models';

export function Abort():Promise<void>;

export function ClearSelectedSkill():Promise<void>;

export function CommandMenu(arg1:string):Promise<protocol.CommandMenu>;

export function ContextSnapshot():Promise<runtime.ContextSnapshot>;

export function CurrentModel():Promise<string>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetConfig():Promise<runtime.ConfigView>;

export function GetSkillManagement():Promise<runtime.SkillManagementView>;

export function ListSessions():Promise<Array<runtime.SessionMeta>>;

export function LoadSession(arg1:string):Promise<Array<runtime.DisplayMessage>>;

export function NewSession():Promise<runtime.SessionMeta>;

export function ReadImageBase64(arg1:string):Promise<string>;

export function RefreshSkillManagement():Promise<runtime.SkillManagementView>;

export function ReplyConfirm(arg1:string,arg2:boolean):Promise<void>;

export function ReplyConfirmDecision(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function ReplyQuestion(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ResolveModelProfile(arg1:runtime.ModelSpec):Promise<runtime.ModelProfile>;

export function SaveConfig(arg1:runtime.ConfigView):Promise<runtime.ConfigView>;

export function SelectSkill(arg1:string):Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function SetPluginEnabled(arg1:string,arg2:boolean):Promise<runtime.SkillManagementView>;

export function SwitchModel(arg1:string):Promise<string>;

export function MCPAuthorizationAction(name: string, action: string): Promise<void>;
